### ISSUE TITLE
Improve Load from Disk performance.

### ISSUE THREAD

**Issue by dft-dutoit** [jla-gardner/load-atoms#28]
Improve load from disk performance by concatenating xyz files to a single file upon loading. This can then be read in the same way as multiple files, just with an index=":"

**Comment by jla-gardner** [comment]
It would greatly surprise me if this led to large time savings given that our files are already quite large. (To be clear, we aren't saving each structure individually, but rather batches of structures within files).

**Comment by jla-gardner** [comment]
Timing benchmarks using the `C-SYNTH-23M` database. This is currently stored as 546 individual files, each containing 211 snapshots of a 200 atom trajectory, amounting to ~3GB of raw text.

Reading each file separately and concatenating takes 54s on my MacBook, whereas reading a concatenated file takes 52s:

Multi-files:
<img width="300" alt="Screenshot 2023-05-18 at 07 28 51" src="https://github.com/jla-gardner/load-atoms/assets/92588218/e39fe011-eb85-4b79-a80a-60d73c5082e5">

Single file:
<img width="300" alt="Screenshot 2023-05-18 at 07 34 30" src="https://github.com/jla-gardner/load-atoms/assets/92588218/19bf6bba-6deb-4349-a935-89daef0e0995">

**Comment by dft-dutoit** [comment]
Could you try utilizing an ASE trajectory/bundle trajectory file? The read/write performance may be improved
